// Code generated by Slice Machine. DO NOT EDIT.

import ProfileCardFront from './ProfileCardFront/index.svelte';
import ProfileCard from './ProfileCard/index.svelte';

export const components = {
	profile_card_front: ProfileCardFront,
	rich_text: ProfileCard
};
